apiVersion: v1
kind: Secret
metadata:
  name: twilio-credentials
  namespace: saferoute
type: Opaque
stringData:
  TWILIO_ACCOUNT_SID: "your_account_sid_here"
  TWILIO_AUTH_TOKEN: "your_auth_token_here"
  TWILIO_PHONE_NUMBER: "+1234567890"