apiVersion: v1
kind: Service
metadata:
  name: feedback
  namespace: saferoute
  labels:
    app: feedback
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 20004
    protocol: TCP
    name: http
  selector:
    app: feedback

