apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  namespace: saferoute
  labels:
    app: rabbitmq
    service: management
spec:
  type: ExternalName
  externalName: rabbitmq.data.svc.cluster.local
  ports:
  - port: 15672
    targetPort: 15672
    name: management
    protocol: TCP

