apiVersion: v1
kind: ConfigMap
metadata:
  name: routing-service-config
  namespace: saferoute
data:
  database.name: "saferoute"
  # TODO: Add your routing API keys here
  google.maps.api.enabled: "false"
  log.level: "info"
  # OpenRouteService configuration
  ors.api.enabled: "true"

