apiVersion: v1
kind: Service
metadata:
  name: routing-service
  namespace: saferoute
  labels:
    app: routing-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 20002
    protocol: TCP
    name: http
  selector:
    app: routing-service

