apiVersion: v1
kind: ConfigMap
metadata:
  name: user-management-config
  namespace: saferoute
data:
  database.name: "saferoute"
  # TODO: Change to your Auth0 domain
  auth0.domain: "saferoute.eu.auth0.com"
  log.level: "info"

