apiVersion: v1
kind: Service
metadata:
  name: user-management
  namespace: saferoute
  labels:
    app: user-management
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 20000
    protocol: TCP
    name: http
  selector:
    app: user-management

