apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-csi-premium
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: disk.csi.azure.com
parameters:
  skuName: Premium_LRS  # Premium SSD for better performance
  cachingMode: ReadOnly
  fsType: ext4
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain

